version: "3.8"
services:
  rproxy:
    restart: always
    image: nginx:1.19.10-alpine
    volumes:
      - ./rproxy.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    stdin_open: true
    networks:
      - frontend-backend
    depends_on:
      - frontend
      - backend
  
  frontend:
    restart: always
    build: frontend
    networks:
      - frontend-backend
    environment:
      PORT: 80
    #volumes:
    #  - ./frontend/src:/app/src # allow live-debugging

  backend:
    restart: always
    build: backend
    depends_on:
      - database
    networks:
      - backend-database
      - frontend-backend
    environment:
      PORT: 80
      DB_CONNECTION: mongodb://database:27017/aws
    #volumes:
    #  - ./backend/src:/app/src # allow live-debugging

  database:
    restart: always
    image: mongo:4.4.4
    networks:
      - backend-database
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    #  - ./data:/data/db
networks:
  frontend-backend:
  backend-database: